version: "2"
linters:
  # https://golangci-lint.run/docs/configuration/file/#linters-configuration
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: none
  enable:
    - govet
    - revive
    - misspell
    - ineffassign
    - bodyclose
    - wsl_v5
    - funlen
    - depguard
  disable:
    - wsl
    - cyclop
    - mnd
  # https://golangci-lint.run/docs/linters/configuration/
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
      # settings:
      #   shadow:
      #     strict: true
    # https://golangci-lint.run/docs/linters/configuration/#depguard
    funlen:
      lines: 120
      statements: 60
      ignore-comments: true
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/rancher
            - github.com/rancherlabs
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - "check-private-receivers"
            - "disable-stuttering-check"
            - "say-repetitive-instead-of-stutters"
            - "check-public-interface"
            - "disable-checks-on-constants"
            - "disable-checks-on-functions"
            - "disable-checks-on-methods"
            - "disable-checks-on-types"
            - "disable-checks-on-variables"
formatters:
  enable:
    - goimports
    - gofumpt
#   settings:
#     gofmt:
#       simplify: false
issues:
  fix: true
