{{- $files := .Files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-files
data:
{{- range $path, $_ := .Files.Glob "test-files/**.{js,mjs,ts}" }}
  {{- if $path }}
  {{- $key := (trimPrefix "test-files/" $path) | replace "/" "__" }}
  {{ $key }}: |-
{{ $files.Get $path | indent 4 }}
  {{- end }}
{{- end }}
